version: "3.9"
services:
  dev:
    build: 
      context: ./airflow
      target: dev
    entrypoint: sh -c "bin/run.sh"
    ports:
        - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
